services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qafzah_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: always
